#!/usr/bin/env bash
# ============================================================
# 模块: keepalived (管理面多机可靠性 / VIP 主备)
#
# 设计:
#   - 仅 master_nodes 节点部署 keepalived，通过 VRRP 协议在 master 节点间
#     竞争 ingress_virtual_ip（VIP），保证管理面统一入口高可用
#   - 管理面服务（agent-registry / jiuwenswarm-gateway / jiuwenswarm-web）
#     为主备部署: 仅 VIP 持有节点（VRRP MASTER）运行，standby 不运行
#   - 主备切换由 keepalived 的 notify_master / notify_backup / notify_fault
#     回调 keepalived-notify.sh 驱动（启/停管理面 systemd unit）
#   - 管理面服务的存活由 systemd 自身监控并异常拉起，keepalived 不做管理面
#     健康探测，只负责节点级故障（宕机/断网）经 VRRP 通告触发 VIP 漂移
#   - 单播（unicast_peer）模式组网，不依赖交换机组播能力
#   - 非抢占（nopreempt）模式: 原 master 恢复后不夺回 VIP，避免二次切换抖动
#
# 前置:
#   - keepalived 由上游预装（openEuler: yum install keepalived）
#   - config.yaml 的 master_nodes 配置 2 个节点（主备）、ingress_virtual_ip 配置 VIP
#   - 单机模式（master_nodes 单节点或 VIP 为 127.0.0.1）自动跳过
#
# 钩子函数: keepalived_up / keepalived_down / keepalived_install /
#           keepalived_uninstall / keepalived_status
# ============================================================

KA_CONF_DIR="/etc/keepalived"
KA_CONF="${KA_CONF_DIR}/keepalived.conf"
KA_NOTIFY="${KA_CONF_DIR}/agentos-notify.sh"
KA_SVC="keepalived"
KA_VRID="${KEEPALIVED_VRID:-51}"
KA_ADVERT_INT="${KEEPALIVED_ADVERT_INT:-1}"
KA_AUTH_PASS="${KEEPALIVED_AUTH_PASS:-agentos51}"

_ka_has_systemd() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

_ka_python() {
    command -v "python${YR_PYTHON_VERSION:-3.11}" 2>/dev/null || command -v python3 2>/dev/null
}

_ka_cfg() {
    "$(_ka_python)" "${SCRIPT_DIR}/scripts/config.py" "$@"
}

# 是否启用 keepalived：多机 HA（master_nodes >= 2 且 VIP 非回环）才启用
_ka_enabled() {
    local vip masters
    vip=$(_ka_cfg ingress-vip 2>/dev/null) || return 1
    case "${vip}" in
        127.*|""|0.0.0.0) return 1 ;;
    esac
    masters=$(_ka_cfg master-nodes 2>/dev/null) || return 1
    [ "$(echo "${masters}" | wc -w)" -ge 2 ]
}

# 本机是否为 master 节点
_ka_is_master_node() {
    _ka_cfg is-master-node >/dev/null 2>&1
}

# 本机在 master_nodes 中的序号（0 起）；用于 priority 推导
_ka_master_index() {
    _ka_cfg master-index 2>/dev/null
}

# ===== 包检测函数（兼容 RPM 和 DEB，参照 moosefs_deploy.sh）=====
# 注意: 优先用 dpkg 检测，因为 Ubuntu 上可能装了 rpm 命令但包实际是 DEB 包。
# 只要任一包管理器找到即视为已安装。
_ka_check_pkg_installed() {
    local pkg="$1"
    if command -v dpkg >/dev/null 2>&1 && dpkg -s "${pkg}" >/dev/null 2>&1; then
        return 0
    fi
    if command -v rpm >/dev/null 2>&1 && rpm -q "${pkg}" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

# 探测持有本机 IP 的网卡（VRRP interface）
_ka_iface_of_local_ip() {
    local local_ip="$1" iface
    iface=$(ip -o -4 addr show 2>/dev/null | awk -v ip="${local_ip}" '$4 ~ ip"/" {print $2; exit}')
    [ -z "${iface}" ] && iface=$(ip route get 1 2>/dev/null | awk '{for(i=1;i<NF;i++) if($i=="dev") print $(i+1); exit}')
    echo "${iface}"
}

# 生成 keepalived.conf
# priority: master_nodes[0]=150, [1]=140, ...（每个后继节点 -10）
# state 统一 BACKUP + nopreempt: 初次由 priority 决出 MASTER，故障恢复后不抢回
_ka_generate_conf() {
    local vip local_ip idx priority iface peers peer masters
    vip=$(_ka_cfg ingress-vip) || error "Failed to read ingress_virtual_ip"
    local_ip=$(_ka_cfg local-ip) || error "Failed to get local IP"
    idx=$(_ka_master_index) || error "Failed to derive master index (is this host in master_nodes?)"
    priority=$((150 - idx * 10))
    iface=$(_ka_iface_of_local_ip "${local_ip}")
    [ -n "${iface}" ] || error "Cannot detect network interface for local IP ${local_ip}"

    masters=$(_ka_cfg master-nodes) || error "Failed to read master_nodes"
    peers=""
    for peer in ${masters}; do
        [ "${peer}" = "${local_ip}" ] && continue
        peers="${peers}        ${peer}
"
    done

    info "keepalived.conf: vip=${vip}, iface=${iface}, priority=${priority} (index=${idx}), vrid=${KA_VRID}"

    mkdir -p "${KA_CONF_DIR}"
    cat > "${KA_CONF}" <<EOF
! AgentOS managed keepalived configuration (generated by deploy/keepalived/module.sh)
global_defs {
    router_id agentos_$(hostname)
    script_user root
    enable_script_security
}

vrrp_instance AGENTOS_INGRESS {
    # 统一 BACKUP + nopreempt: 由 priority 决出初始 MASTER，
    # 原 master 故障恢复后不抢回 VIP，避免二次切换
    state BACKUP
    nopreempt
    interface ${iface}
    virtual_router_id ${KA_VRID}
    priority ${priority}
    advert_int ${KA_ADVERT_INT}

    authentication {
        auth_type PASS
        auth_pass ${KA_AUTH_PASS}
    }

    # 单播组网（不依赖交换机组播）
    unicast_src_ip ${local_ip}
    unicast_peer {
${peers}    }

    virtual_ipaddress {
        ${vip}
    }

    # 主备切换回调: 管理面服务随 VRRP 角色启停
    # （服务存活由 systemd 监控拉起，keepalived 不做管理面健康探测）
    notify_master "${KA_NOTIFY}"
    notify_backup "${KA_NOTIFY}"
    notify_fault  "${KA_NOTIFY}"
}
EOF
    chmod 644 "${KA_CONF}"
}

# ===== install: 校验依赖 + 安装 notify 脚本 + 生成配置 =====
keepalived_install() {
    if ! _ka_enabled; then
        info "keepalived disabled (single-node or loopback VIP), skipping install"
        return 0
    fi
    if ! _ka_is_master_node; then
        info "This host is NOT a master node, skipping keepalived install"
        return 0
    fi

    _ka_has_systemd || error "keepalived module requires systemd"

    # 验证 keepalived 包已由上游预装（兼容 RPM 和 DEB，参照 moosefs_deploy.sh）
    # install 阶段不代为 yum/apt 安装，与"依赖包由上游预装"的部署约定保持一致
    if ! _ka_check_pkg_installed keepalived; then
        error "keepalived package not installed. Please install it before running this script (e.g. yum install -y keepalived)."
    fi
    success "keepalived package verified"

    # KA_CONF_DIR: 下方写入 notify 脚本; /var/log/agentos: notify 运行时写日志
    mkdir -p "${KA_CONF_DIR}" /var/log/agentos

    # 安装 notify 脚本（enable_script_security 要求 root 属主 + 非 group/other 可写）
    # 注入 agentos.sh 的绝对路径：直接取 agentos.sh 定义的 SCRIPT_DIR（module.sh 被其 source，
    # SCRIPT_DIR 即当前执行的 deploy/ 目录），不假定任何固定安装位置。
    {
        sed "s|@AGENTOS_SH@|${SCRIPT_DIR}/agentos.sh|g" "${SCRIPT_DIR}/keepalived/keepalived-notify.sh"
    } > "${KA_NOTIFY}"
    chown root:root "${KA_NOTIFY}"
    chmod 700 "${KA_NOTIFY}"

    _ka_generate_conf

    # 管理面服务不随开机自启，统一交给 keepalived notify 驱动
    # （三个管理面 unit 的 ExecStartPre 检查 VIP 持有作为二道防线）
    success "keepalived installed (conf: ${KA_CONF})"
}

# ===== up: 启动 keepalived（VIP 竞争 + notify 驱动管理面启停） =====
keepalived_up() {
    if ! _ka_enabled; then
        info "keepalived disabled (single-node or loopback VIP), skipping up"
        return 0
    fi
    if ! _ka_is_master_node; then
        info "This host is NOT a master node, skipping keepalived up"
        return 0
    fi

    [ -f "${KA_CONF}" ] || error "keepalived.conf not found at ${KA_CONF}; run 'install' first"

    # 校验配置合法性（keepalived -t 配置测试）
    keepalived -t -f "${KA_CONF}" >/dev/null 2>&1 \
        || warning "keepalived config test failed or unsupported (-t); continuing"

    systemctl enable --now "${KA_SVC}" || error "Failed to start ${KA_SVC}"

    local i
    for i in $(seq 1 10); do
        systemctl is-active --quiet "${KA_SVC}" && break
        sleep 1
    done
    systemctl is-active --quiet "${KA_SVC}" \
        || error "${KA_SVC} not active, see: journalctl -u ${KA_SVC}"

    success "keepalived up (VIP arbitration in progress; management services follow VRRP role)"
}

# ===== down: 停 keepalived（释放 VIP；管理面服务由调用方 down 钩子逆序停止） =====
keepalived_down() {
    if ! _ka_enabled || ! _ka_is_master_node; then
        info "keepalived not applicable on this host, skipping down"
        return 0
    fi
    _ka_has_systemd || { warning "systemd not available, nothing to stop"; return 0; }

    # 停 keepalived 会释放 VIP，peer 节点将接管并由其 notify_master 拉起管理面
    systemctl stop "${KA_SVC}" 2>/dev/null \
        && success "keepalived stopped (VIP released, peer will take over)" \
        || warning "keepalived not running"
}

# ===== uninstall: 停服务 + 清理配置与脚本 =====
keepalived_uninstall() {
    if ! _ka_is_master_node 2>/dev/null; then
        info "This host is NOT a master node, skipping keepalived uninstall"
        return 0
    fi
    if _ka_has_systemd; then
        systemctl disable --now "${KA_SVC}" 2>/dev/null || true
        systemctl reset-failed "${KA_SVC}" 2>/dev/null || true
    fi
    rm -f "${KA_CONF}" "${KA_NOTIFY}"
    success "keepalived uninstalled (binary/package preserved)"
}

# ===== status: 只读探测 keepalived 状态 + VRRP 角色 =====
# 输出格式: keepalived|keepalived.service|<state>|<detail>
keepalived_status() {
    local svc="${KA_SVC}.service"

    if ! _ka_enabled 2>/dev/null; then
        echo "keepalived|${svc}|n/a|disabled (single-node or loopback VIP)"
        return 0
    fi
    if ! _ka_is_master_node 2>/dev/null; then
        echo "keepalived|${svc}|n/a|not master node"
        return 0
    fi
    if ! _ka_has_systemd; then
        echo "keepalived|${svc}|stopped|systemd required"
        return 0
    fi
    if [ ! -f "${KA_CONF}" ]; then
        echo "keepalived|${svc}|stopped|conf not found"
        return 0
    fi

    if systemctl is-failed --quiet "${KA_SVC}" 2>/dev/null; then
        echo "keepalived|${svc}|failed|unit failed"
        return 1
    fi

    if systemctl is-active --quiet "${KA_SVC}" 2>/dev/null; then
        # VRRP 角色: 本机持有 VIP 即 MASTER，否则 BACKUP
        local vip role
        vip=$(_ka_cfg ingress-vip 2>/dev/null)
        role="BACKUP"
        if [ -n "${vip}" ] && ip addr show 2>/dev/null | grep -qw "${vip}"; then
            role="MASTER"
        fi
        echo "keepalived|${svc}|running|vrrp role: ${role} (vip: ${vip:-unknown})"
        return 0
    fi

    echo "keepalived|${svc}|stopped|unit inactive"
    return 0
}
