#!/usr/bin/env python3
# coding: utf-8
"""Inference Service Control API Server - FastAPI wrapper for inference_ctl.py."""

import argparse
import asyncio
import json
import logging
import re
import shutil
import threading
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import APIRouter, Depends, FastAPI, HTTPException

import inference_ctl as ctl
from auth import TokenData, require_admin
from models import ApiResponse

SCRIPT_DIR = Path(__file__).parent
logger = logging.getLogger("node-service.server")
CONFIG_DIR = SCRIPT_DIR / "config"
TEMPLATES_DIR = SCRIPT_DIR / "templates"
USER_TEMPLATES_DIR = SCRIPT_DIR / "user_templates"
SIMPLIFIED_CONFIG = CONFIG_DIR / "config.json"       # API 读写的简化配置
USER_CONFIG_DIR = CONFIG_DIR / "vllm"
ACTIVE_USER_CONFIG = USER_CONFIG_DIR / "user_config.json"

# ── Background start state ──────────────────────────────────────────────
_start_lock = threading.Lock()
_start_in_progress = False
_start_progress = {"status": "idle", "message": "", "error": None}


class ArgsNamespace:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)


def _load_config() -> dict:
    """Load simplified config from config.json."""
    with open(SIMPLIFIED_CONFIG, "r", encoding="utf-8") as f:
        return json.load(f)


def _save_config(cfg: dict):
    """Save simplified config only. user_config.json will be generated by ctl.cmd_start."""
    with open(SIMPLIFIED_CONFIG, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=4, ensure_ascii=False)


def _merge_config(cfg: dict, patch: dict):
    """Merge partial update into config (same semantics as PUT /vllm/config)."""
    for section, values in patch.items():
        if section in cfg and isinstance(values, dict) and isinstance(cfg[section], dict):
            cfg[section].update(values)
        elif section in cfg:
            cfg[section] = values


def _build_start_args(cfg: dict) -> argparse.Namespace:
    """Build argparse.Namespace for cmd_start from simplified config."""
    model = cfg.get("model", {})
    deploy = cfg.get("deploy", {})
    parallel = cfg.get("parallel", {})
    inference = cfg.get("inference", {})
    fmt = cfg.get("format", {})
    ports = cfg.get("ports", {})

    return ArgsNamespace(
        config_file="",
        weight_path=model.get("weight_path", ""),
        model_path=model.get("model_path", ""),
        model_name=model.get("model_name", ""),
        image=deploy.get("image", ""),
        npu_num=deploy.get("npu_num", 0),
        tensor_parallel_size=parallel.get("tensor_parallel_size"),
        data_parallel_size=parallel.get("data_parallel_size"),
        quantization=parallel.get("quantization") or None,
        enable_expert_parallel=parallel.get("enable_expert_parallel"),
        gpu_memory_utilization=parallel.get("gpu_memory_utilization"),
        max_model_len=inference.get("max_model_len"),
        max_num_batched_tokens=inference.get("max_num_batched_tokens"),
        max_num_seqs=inference.get("max_num_seqs"),
        enforce_eager=inference.get("enforce_eager"),
        tokenizer_mode=fmt.get("tokenizer_mode") or None,
        tool_call_parser=fmt.get("tool_call_parser") or None,
        reasoning_parser=fmt.get("reasoning_parser") or None,
        trust_remote_code=fmt.get("trust_remote_code"),
        controller_port=ports.get("controller_port", 2026),
        coordinator_infer_port=ports.get("coordinator_infer_port", 1025),
        coordinator_mgmt_port=ports.get("coordinator_mgmt_port", 1030),
        coordinator_obs_port=ports.get("coordinator_obs_port", 1029),
        node_manager_port=ports.get("node_manager_port", 3026),
        base_port=ports.get("base_port", 10000),
    )


def _start_in_background():
    """Run inference_ctl.cmd_start in a background thread."""
    global _start_in_progress, _start_progress
    try:
        def on_progress(msg):
            _start_progress["message"] = msg
            if "starting container" in msg.lower():
                _start_progress["status"] = "starting"
            elif "waiting" in msg.lower():
                _start_progress["status"] = "waiting"
            elif "extracting" in msg.lower() or "cleaning" in msg.lower() or "applying" in msg.lower():
                _start_progress["status"] = "preparing"

        _start_progress = {"status": "pulling", "message": "Preparing image...", "error": None}
        cfg = _load_config()

        _start_progress["message"] = "Stopping existing container..."
        ctl.stop_container()

        config_path = None
        if ACTIVE_USER_CONFIG.exists():
            _start_progress["message"] = "Using existing user config..."
            logger.info("using active user config: %s", ACTIVE_USER_CONFIG)
            config_path = str(ACTIVE_USER_CONFIG)
        else:
            args = _build_start_args(cfg)

            _start_progress["message"] = "Resolving vLLM image..."
            default_resources = str(SCRIPT_DIR / ".." / "ascend_deployer" / "resources")
            image = ctl.resolve_vllm_image(cfg.get("deploy", {}).get("image", ""), default_resources)

            _start_progress["message"] = "Saving config..."
            ctl.save_config_from_args(args, image)

        _start_progress["message"] = "Starting vLLM container..."
        ctl.start_from_config(config_path=config_path, on_progress=on_progress)
        _start_progress = {"status": "ready", "message": "vLLM instance ready!", "error": None}
    except Exception as e:
        _start_progress = {"status": "failed", "message": "", "error": str(e)}
    finally:
        _start_in_progress = False


# ── Inference Router ────────────────────────────────────────────────────

vllm_router = APIRouter(prefix="/inference", tags=["inference"])


@vllm_router.get("/config", summary="Get current config")
async def get_config(_user: TokenData = Depends(require_admin)):
    """Return the current simplified config."""
    return _load_config()


@vllm_router.put("/config", response_model=ApiResponse, summary="Update config")
async def update_config(body: dict, _user: TokenData = Depends(require_admin)):
    """
    Update config fields. Only send fields you want to change, e.g.:
    {
        "model": {"model_name": "new-name", "weight_path": "/data/weights"},
        "parallel": {"tensor_parallel_size": 8}
    }
    """
    cfg = _load_config()
    _merge_config(cfg, body)
    _save_config(cfg)
    _sync_user_config(cfg)
    return ApiResponse(success=True, message="配置已保存")


@vllm_router.post("/start", response_model=ApiResponse, summary="Start vLLM container")
async def start_container(body: dict = None, _user: TokenData = Depends(require_admin)):
    """Start vLLM container. Returns immediately (202).

    Optional body: partial config fields to merge before start, e.g.:
    {"model": {"model_name": "new"}, "parallel": {"tensor_parallel_size": 8}}
    """
    global _start_in_progress, _start_progress
    with _start_lock:
        if _start_in_progress:
            raise HTTPException(status_code=409, detail="启动操作正在进行中，请稍候")
        _start_in_progress = True

    # validate config after acquiring lock
    try:
        cfg = _load_config()
        if body:
            _merge_config(cfg, body)
            _save_config(cfg)
            _sync_user_config(cfg)

        model = cfg.get("model", {})
        if not model.get("weight_path") or not model.get("model_path") or not model.get("model_name"):
            raise ValueError("缺少必填字段: model.weight_path, model.model_path, model.model_name")
    except Exception as exc:
        _start_in_progress = False
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    _start_progress = {"status": "queued", "message": "Start request accepted", "error": None}
    t = threading.Thread(target=_start_in_background, daemon=True)
    t.start()
    return ApiResponse(success=True, message="启动请求已接受，请轮询 GET /inference/status 获取进度")


@vllm_router.post("/stop", response_model=ApiResponse, summary="Stop vLLM container")
async def stop_container(_user: TokenData = Depends(require_admin)):
    """Stop and remove the running vLLM container."""
    try:
        await asyncio.to_thread(ctl.cmd_stop, None)
        return ApiResponse(success=True, message="容器已停止")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e


@vllm_router.post("/restart", response_model=ApiResponse, summary="Restart vLLM container")
async def restart_container(body: dict = None, _user: TokenData = Depends(require_admin)):
    """Stop then start the container. Returns immediately (202).

    Optional body: partial config fields to merge before restart.
    """
    global _start_in_progress, _start_progress
    with _start_lock:
        if _start_in_progress:
            raise HTTPException(status_code=409, detail="启动操作正在进行中，请稍候")
        _start_in_progress = True

    # validate config and merge optional body
    try:
        cfg = _load_config()
        if body:
            _merge_config(cfg, body)
            _save_config(cfg)
            _sync_user_config(cfg)

        model = cfg.get("model", {})
        if not model.get("weight_path") or not model.get("model_path") or not model.get("model_name"):
            raise ValueError("缺少必填字段: model.weight_path, model.model_path, model.model_name")
    except Exception as exc:
        _start_in_progress = False
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    _start_progress = {"status": "queued", "message": "Restart request accepted", "error": None}
    t = threading.Thread(target=_start_in_background, daemon=True)
    t.start()
    return ApiResponse(success=True, message="重启请求已接受，请轮询 GET /inference/status 获取进度")


@vllm_router.get("/status", summary="Get container status")
async def get_status(_user: TokenData = Depends(require_admin)):
    """Get current container and service status."""
    result = {
        "container": "not running",
        "engine": "unknown",
    }
    rc, out, _ = ctl.run_cmd(f"docker inspect -f '{{{{.State.Status}}}}' {ctl.CONTAINER_NAME}")
    if rc == 0:
        result["container"] = out
        rc2, _, _ = ctl.run_cmd(
            f"docker exec {ctl.CONTAINER_NAME} ps aux | grep -v grep | grep mindieservice_daemon > /dev/null"
        )
        if rc2 == 0:
            result["engine"] = "mindie_motor"
        else:
            rc3, _, _ = ctl.run_cmd(
                f"docker exec {ctl.CONTAINER_NAME} ps aux | grep -v grep | grep -E 'python|boot.sh' > /dev/null"
            )
            result["engine"] = "vllm" if rc3 == 0 else "not_detected"
        rc4, logs, _ = ctl.run_cmd(f"docker logs --tail 10 {ctl.CONTAINER_NAME}")
        if rc4 == 0:
            result["recent_logs"] = logs
    result["config"] = _load_config()
    if _start_in_progress:
        result["start_progress"] = _start_progress
    return result


@vllm_router.get("/health", summary="Health check")
async def health(_user: TokenData = Depends(require_admin)):
    """Check if container is running."""
    rc, out, _ = ctl.run_cmd(f"docker inspect -f '{{{{.State.Status}}}}' {ctl.CONTAINER_NAME}")
    running = rc == 0 and "running" in out
    return {"healthy": running, "container": ctl.CONTAINER_NAME}


@vllm_router.get("/logs", summary="Get container logs")
async def get_logs(lines: int = 50, _user: TokenData = Depends(require_admin)):
    """Get recent container logs."""
    rc, out, _ = ctl.run_cmd(f"docker logs --tail {lines} {ctl.CONTAINER_NAME}")
    if rc != 0:
        raise HTTPException(status_code=404, detail="容器未运行或日志不可用")
    return {"logs": out.splitlines()}


# ── Template helpers ────────────────────────────────────────────────────

_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")

# simplified config field → user_config.json path
_EC = ["motor_engine_union_config", "engine_config"]
_DP = ["motor_deploy_config"]
_CC = ["motor_controller_config", "api_config"]
_OC = ["motor_coordinator_config", "api_config"]
_NM = ["motor_engine_union_config", "motor_nodemanger_config"]
_USER_CONFIG_MAPPING = {
    "model.weight_path": _DP + ["weight_mount_path"],
    "model.model_path": _EC + ["model"],
    "model.model_name": _EC + ["served-model-name"],
    "deploy.image": _DP + ["image_name"],
    "deploy.npu_num": _DP + ["hybrid_pod_npu_num"],
    "parallel.tensor_parallel_size": _EC + ["tensor-parallel-size"],
    "parallel.data_parallel_size": _EC + ["data-parallel-size"],
    "parallel.gpu_memory_utilization": _EC + ["gpu-memory-utilization"],
    "parallel.quantization": _EC + ["quantization"],
    "inference.max_model_len": _EC + ["max-model-len"],
    "inference.max_num_batched_tokens": _EC + ["max-num-batched-tokens"],
    "inference.max_num_seqs": _EC + ["max-num-seqs"],
    "inference.enforce_eager": _EC + ["enforce-eager"],
    "format.tokenizer_mode": _EC + ["tokenizer-mode"],
    "format.tool_call_parser": _EC + ["tool-call-parser"],
    "format.reasoning_parser": _EC + ["reasoning-parser"],
    "format.trust_remote_code": _EC + ["trust-remote-code"],
    "ports.controller_port": _CC + ["controller_api_port"],
    "ports.coordinator_infer_port": _OC + ["coordinator_api_infer_port"],
    "ports.coordinator_mgmt_port": _OC + ["coordinator_api_mgmt_port"],
    "ports.coordinator_obs_port": _OC + ["coordinator_obs_port"],
    "ports.node_manager_port": _NM + ["api_config", "node_manager_port"],
    "ports.base_port": _NM + ["endpoint_config", "base_port"],
}


def _set_nested(d: dict, path: list, value):
    for key in path[:-1]:
        d = d.setdefault(key, {})
    d[path[-1]] = value


def _ensure_dirs():
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    USER_TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    _migrate_old_templates()


def _simplified_to_params(cfg: dict) -> dict:
    """Convert simplified config to params dict for build_user_config."""
    model = cfg.get("model", {})
    deploy = cfg.get("deploy", {})
    parallel = cfg.get("parallel", {})
    inference = cfg.get("inference", {})
    fmt = cfg.get("format", {})
    ports = cfg.get("ports", {})
    params = {}
    if model.get("weight_path"):
        params["weight_path"] = model["weight_path"]
    if model.get("model_path"):
        params["model_path"] = model["model_path"]
    if model.get("model_name"):
        params["model_name"] = model["model_name"]
    if deploy.get("image"):
        params["image_name"] = deploy["image"]
    if deploy.get("npu_num"):
        params["npu_num"] = deploy["npu_num"]
    for key in ("tensor_parallel_size", "data_parallel_size", "gpu_memory_utilization",
                "enable_expert_parallel", "quantization"):
        val = parallel.get(key)
        if val is not None:
            params[key] = val
    for key in ("max_model_len", "max_num_batched_tokens", "max_num_seqs", "enforce_eager"):
        val = inference.get(key)
        if val is not None:
            params[{"max_model_len": "max-model-len", "max_num_batched_tokens": "max-num-batched-tokens",
                    "max_num_seqs": "max-num-seqs", "enforce_eager": "enforce-eager"}[key]] = val
    for key in ("tokenizer_mode", "tool_call_parser", "reasoning_parser", "trust_remote_code"):
        val = fmt.get(key)
        if val is not None:
            params[{"tokenizer_mode": "tokenizer-mode", "tool_call_parser": "tool-call-parser",
                    "reasoning_parser": "reasoning-parser", "trust_remote_code": "trust-remote-code"}[key]] = val
    for key in ("controller_port", "coordinator_infer_port", "coordinator_mgmt_port",
                "coordinator_obs_port", "node_manager_port", "base_port"):
        val = ports.get(key)
        if val is not None:
            params[key] = val
    return params


def _migrate_old_templates():
    """Migrate old single-file templates (*.json directly in templates/) to folder format."""
    try:
        hw = ctl.detect_hardware_type()
    except RuntimeError:
        hw = "800I_A3"
    npu_num = ctl.default_npu_num(hw)

    for f in sorted(TEMPLATES_DIR.glob("*.json")):
        try:
            with open(f, "r", encoding="utf-8") as fp:
                data = json.load(fp)
        except (json.JSONDecodeError, OSError):
            continue
        folder_name = f.stem
        folder = TEMPLATES_DIR / folder_name
        if folder.exists():
            f.unlink()
            continue
        folder.mkdir(parents=True, exist_ok=True)
        template_cfg = data.get("config", {})
        template_meta = {
            "description": data.get("description", ""),
            "source": "system",
            "config": template_cfg,
        }
        with open(folder / "template.json", "w", encoding="utf-8") as fp:
            json.dump(template_meta, fp, indent=4, ensure_ascii=False)
        params = _simplified_to_params(template_cfg)
        params = {k: v for k, v in params.items() if v is not None}
        try:
            user_cfg = ctl.build_user_config(params, hw, npu_num)
        except (KeyError, TypeError):
            user_cfg = ctl.build_user_config({}, hw, npu_num)
        with open(folder / "user_config.json", "w", encoding="utf-8") as fp:
            json.dump(user_cfg, fp, indent=4, ensure_ascii=False)
        f.unlink()
        logger.info("migrated old template: %s -> %s/", f.name, folder_name)


def _sync_user_config(cfg: dict):
    """Sync simplified config fields into active user_config.json."""
    if not ACTIVE_USER_CONFIG.exists():
        return
    try:
        with open(ACTIVE_USER_CONFIG, "r", encoding="utf-8") as f:
            uc = json.load(f)
    except (json.JSONDecodeError, OSError):
        return
    for flat_key, path in _USER_CONFIG_MAPPING.items():
        section, field = flat_key.split(".", 1)
        if section in cfg and isinstance(cfg[section], dict) and field in cfg[section]:
            _set_nested(uc, path, cfg[section][field])
    with open(ACTIVE_USER_CONFIG, "w", encoding="utf-8") as f:
        json.dump(uc, f, indent=4, ensure_ascii=False)


def _load_templates_from_dir(directory: Path, source: str) -> list[dict]:
    """Load all templates from subfolders in a directory."""
    templates = []
    if not directory.exists():
        return templates
    for folder in sorted(p for p in directory.iterdir() if p.is_dir()):
        meta_file = folder / "template.json"
        if not meta_file.exists():
            continue
        try:
            with open(meta_file, "r", encoding="utf-8") as fp:
                data = json.load(fp)
        except (json.JSONDecodeError, OSError):
            continue
        data["name"] = folder.name
        data["source"] = source
        templates.append(data)
    return templates


def _find_template(name: str) -> tuple[Path | None, str]:
    """Find a template folder by name. Returns (folder_path, source) or (None, '')."""
    user_folder = USER_TEMPLATES_DIR / name
    if user_folder.is_dir() and (user_folder / "template.json").exists():
        return user_folder, "user"
    sys_folder = TEMPLATES_DIR / name
    if sys_folder.is_dir() and (sys_folder / "template.json").exists():
        return sys_folder, "system"
    return None, ""


# ── Template routes ─────────────────────────────────────────────────────


@vllm_router.get("/templates", summary="List all templates")
async def list_templates(_user: TokenData = Depends(require_admin)):
    """Return all available templates (system presets + user-created)."""
    _ensure_dirs()
    templates = []
    for t in _load_templates_from_dir(TEMPLATES_DIR, "system"):
        templates.append({"name": t["name"], "description": t.get("description", ""), "source": "system"})
    for t in _load_templates_from_dir(USER_TEMPLATES_DIR, "user"):
        templates.append({"name": t["name"], "description": t.get("description", ""), "source": "user"})
    return {"templates": templates}


@vllm_router.get("/templates/{name}", summary="Get template content")
async def get_template(name: str, _user: TokenData = Depends(require_admin)):
    """Get the full config of a named template."""
    folder, _ = _find_template(name)
    if folder is None:
        raise HTTPException(status_code=404, detail=f"模板不存在: {name}")
    with open(folder / "template.json", "r", encoding="utf-8") as f:
        data = json.load(f)
    data["name"] = name
    return data


@vllm_router.post("/templates", response_model=ApiResponse, summary="Save current config as template")
async def save_template(body: dict, _user: TokenData = Depends(require_admin)):
    """Save the current config + user_config as a named template folder.

    Body: {"name": "my-config", "description": "optional description"}
    """
    _ensure_dirs()

    template_name = (body.get("name") or "").strip()
    description = (body.get("description") or "").strip()

    if not template_name:
        raise HTTPException(status_code=400, detail="模板名称不能为空")
    if not _NAME_RE.match(template_name):
        raise HTTPException(status_code=400, detail="模板名称只能包含字母、数字、下划线和连字符")
    if len(template_name) > 100:
        raise HTTPException(status_code=400, detail="模板名称不能超过 100 个字符")

    # Check name conflict by folder name
    existing, _ = _find_template(template_name)
    if existing is not None:
        raise HTTPException(status_code=409, detail=f"模板名称已存在: {template_name}")

    cfg = _load_config()
    folder = USER_TEMPLATES_DIR / template_name
    folder.mkdir(parents=True, exist_ok=False)

    template_meta = {
        "description": description,
        "source": "user",
        "config": cfg,
    }
    with open(folder / "template.json", "w", encoding="utf-8") as f:
        json.dump(template_meta, f, indent=4, ensure_ascii=False)

    if ACTIVE_USER_CONFIG.exists():
        shutil.copy2(ACTIVE_USER_CONFIG, folder / "user_config.json")
    else:
        try:
            hw = ctl.detect_hardware_type()
        except RuntimeError:
            hw = "800I_A3"
        npu_num = ctl.default_npu_num(hw)
        params = _simplified_to_params(cfg)
        params = {k: v for k, v in params.items() if v is not None}
        try:
            user_cfg = ctl.build_user_config(params, hw, npu_num)
        except KeyError:
            user_cfg = ctl.build_user_config({}, hw, npu_num)
        with open(folder / "user_config.json", "w", encoding="utf-8") as f:
            json.dump(user_cfg, f, indent=4, ensure_ascii=False)

    return ApiResponse(success=True, message=f"模板已保存: {template_name}")


@vllm_router.delete("/templates/{name}", response_model=ApiResponse, summary="Delete user template")
async def delete_template(name: str, _user: TokenData = Depends(require_admin)):
    """Delete a user-created template. System presets cannot be deleted."""
    _ensure_dirs()

    folder, source = _find_template(name)
    if folder is None:
        raise HTTPException(status_code=404, detail=f"模板不存在: {name}")

    if source == "system":
        raise HTTPException(status_code=403, detail="系统预设模板不可删除")

    shutil.rmtree(folder)

    return ApiResponse(success=True, message=f"模板已删除: {name}")


@vllm_router.post("/config/apply-template", response_model=ApiResponse, summary="Apply a template")
async def apply_template(body: dict, _user: TokenData = Depends(require_admin)):
    """Apply a template: copy its user_config and simplified config to active config.

    Body: {"name": "template-name"}
    """
    _ensure_dirs()

    template_name = (body.get("name") or "").strip()
    if not template_name:
        raise HTTPException(status_code=400, detail="模板名称不能为空")

    folder, _ = _find_template(template_name)
    if folder is None:
        raise HTTPException(status_code=404, detail=f"模板不存在: {template_name}")

    template_src = folder / "user_config.json"
    if not template_src.exists():
        raise HTTPException(status_code=500, detail=f"模板缺少 user_config.json: {template_name}")

    shutil.copy2(template_src, ACTIVE_USER_CONFIG)

    with open(folder / "template.json", "r", encoding="utf-8") as f:
        meta = json.load(f)
    template_cfg = meta.get("config", {})
    _save_config(template_cfg)

    return ApiResponse(success=True, message=f"模板已应用: {template_name}")


# ── App ──────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(_app: FastAPI):
    yield


app = FastAPI(
    title="Ascend Deployer Control API",
    description="REST API for managing inference services on Ascend NPU",
    version="1.0.0",
    lifespan=lifespan,
)

app.include_router(vllm_router)


@app.get("/health", tags=["system"], summary="Server health")
async def server_health():
    return {"status": "ok"}


def main():
    parser = argparse.ArgumentParser(description="Ascend Deployer Control API Server")
    parser.add_argument("--host", default="0.0.0.0", help="Bind host")
    parser.add_argument("--port", type=int, default=8101, help="Bind port")
    args = parser.parse_args()

    import uvicorn
    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
