scrape_configs:
  - job_name: agent-metrics
    metrics_path: /metrics
    file_sd_configs:
      - files: ["/etc/vm/agent-metrics.json"]

  - job_name: node-exporter
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    file_sd_configs:
      - files: ["/etc/vm/hardware-metrics.json"]
    relabel_configs:
      - source_labels: [exporter]
        regex: node
        action: keep

  - job_name: npu-exporter
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    file_sd_configs:
      - files: ["/etc/vm/hardware-metrics.json"]
    relabel_configs:
      - source_labels: [exporter]
        regex: npu
        action: keep
