apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: agentos-loki
    access: proxy
    url: http://loki:8096
    isDefault: false
    jsonData:
      maxLines: 5000
      derivedFields: []
